--- arch/microblaze/include/asm/Kbuild
+++ arch/microblaze/include/asm/Kbuild
@@ -11,4 +11,3 @@
 generic-y += scatterlist.h
 generic-y += syscalls.h
 generic-y += trace_clock.h
-generic-y += word-at-a-time.h
