--- arch/xtensa/include/asm/Kbuild
+++ arch/xtensa/include/asm/Kbuild
@@ -30,5 +30,4 @@
 generic-y += termios.h
 generic-y += topology.h
 generic-y += trace_clock.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
