--- arch/cris/include/asm/Kbuild
+++ arch/cris/include/asm/Kbuild
@@ -18,5 +18,4 @@
 generic-y += sections.h
 generic-y += trace_clock.h
 generic-y += vga.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
