--- arch/mips/include/asm/Kbuild
+++ arch/mips/include/asm/Kbuild
@@ -18,5 +18,4 @@
 generic-y += trace_clock.h
 generic-y += ucontext.h
 generic-y += user.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
