--- arch/tile/include/asm/Kbuild
+++ arch/tile/include/asm/Kbuild
@@ -41,5 +41,4 @@
 generic-y += termios.h
 generic-y += trace_clock.h
 generic-y += types.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
