--- arch/avr32/include/asm/Kbuild
+++ arch/avr32/include/asm/Kbuild
@@ -21,5 +21,4 @@
 generic-y += topology.h
 generic-y += trace_clock.h
 generic-y += vga.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
