--- arch/hexagon/include/asm/Kbuild
+++ arch/hexagon/include/asm/Kbuild
@@ -59,5 +59,4 @@
 generic-y += ucontext.h
 generic-y += unaligned.h
 generic-y += vga.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
