--- arch/blackfin/include/asm/Kbuild
+++ arch/blackfin/include/asm/Kbuild
@@ -47,5 +47,4 @@
 generic-y += ucontext.h
 generic-y += unaligned.h
 generic-y += user.h
-generic-y += word-at-a-time.h
 generic-y += xor.h
